### PR TITLE
improve queue.StopConsuming()

### PR DESCRIPTION
**Pull request by xujinzheng**
improve queue.StopConsuming(), make sure all fetched message will be consumed correct.

### CODE REVIEW

**Comment by wellle** [comment]
Thank you for your contribution! :+1:

It looks like you are still working on the graceful shutdown. Can you give me some more context of what exactly rmq should offer in that regard?

It looks like you want to block `StopConsuming` until all deliveries are sent to their consumers. Don't you want to wait for all deliveries to be either acked or rejected as well? What if some delivery doesn't make progress?

What is your wait group counting exactly?

I'm also not sure if blocking `StopConsuming` is the right approach. Maybe we want to add something for this purpose, like returning a channel that will be closed when everything is done.

I think we should discuss the requirements of this graceful shutdown in more detail and only then  work on a solution.

And for such a big feature we will need proper tests.

Thanks again, looking forward to your reply.

**Comment by xujinzheng** [comment]
My english is poor, so I try to explain it. :joy: 

I am working on my project of `spirit`, it just like FBP-like(flow based programming), I use message queue to connect each component, so my workmate could development biz component standalone, every component is a standalone process.

the `queue.consume()` , `consumerConsume()` and `consumerBatchConsume()`  are running at go routine, so we should need use wait group to make sure the deliveries will be processed, then could stop correct.

the wait group is make sure all deliveries processed by consumer, then the var `queue.consumingStopped` will be set to `true`, the wait group counter is count the number of deliveries already received but no processed, while one delivery processed, we call wg.Done() to -1. 
When I call `StopConsuming`, it will be block, while all deliveries be processed by consumer, the wait group will continue, so I known it is already stopped, if use non-blocking mode, the queue's message did not consumed completely, so my program did not known when the consume will actually stop.

the block mode is the one way to implement,  we also could implement as following:


rmq:
```go 
StopConsuming() (isStopped <- chan bool, err error)
``` 

my program:
```
isStoppedChan,e:=queue.StopConsuming()

isStopped:=<- isStoppedChan

cleaner.Clean() // just in case.....

exit my program
```


https://github.com/gogap/spirit/blob/feature/add_rmq_support/message_receiver_rmq.go#L168

**Comment by wellle** [comment]
Yeah I think something like this can be done. Instead of a channel, we might also consider returning a wait group that the caller can wait on.

You are asking to stop consuming on a certain queue and to be able to wait for it to finish. Do you think this is sufficient for all related use cases, or would it make sense to think about these related problems as well?

1. Stop only one consumer and make it possible to wait until it's finished (while other consumers on same queue keep going, related to #5)
2. Stop everything related to a rmq connection. Affects every consumer that was started using any queue opened in this connection. Wait until every one of them is done.

And there might be one more caveat: Most likely rmq will only wait until the final `Consumer.Consume` call returns. This assumes that each consumer calls either `Ack`, `Reject` or `Push` synchronously inside the `Consume` function and not in a separate goroutine. But I think that's a fair assumption to make.

**Comment by xujinzheng** [comment]
I think channel is better than wait group for me, because we could simply use `_ <- time.After(time.Second*10)` to set a timeout signal.

my purpose is while my program received signal of TERM, I need call StopConsuming to stop receive deliveries, and if the deliveries already received from redis, I need to finish process these deliveries before my program exited, and it is better to set a stop timeout if we could not StopConsuming success.

**Comment by wellle** [comment]
I believe this has been done in #33. Please let us know if anything is missing in the current implementation of `StopConsuming()` :v:

**Pull request closed without merging**
