### PR TITLE
Upgrade go redis to v8

### PR DESCRIPTION
**Pull request by fmstephe**
Closes https://github.com/adjust/rmq/issues/92

Here we upgrade the go-redis dependency to V8.

We also allow users to provide a custom implementation of rmq.RedisClient. This means users don't _need_ to use the conveniently supported redis client, they can implement this interface using any client they require.

### CODE REVIEW

**Review by wellle — CHANGES_REQUESTED** [review]
Looks good so far.

As discussed let's consider using the context we already have available in delivery.go.

**Review by wellle — APPROVED** [review]
As discussed let's leave it as is 👍

**Comment by narqo** [comment]
From SemVer's perspective, that should be `module github.com/adjust/rmq/v4` since this will change the existing code, forcing the users to update their code.

**Review by narqo — APPROVED** [review]
🔥

**Pull request merged**
